### ISSUE TITLE
Move over to main repo

### ISSUE THREAD

**Issue by Baklap4** [performous/performous-docker#15]
Currently this is managed in a separate repository since we didn't wanna polute the main repository.
However there are some benefits to having this within the main repository, the biggest one being ease of building.

Currently if someone wants to add or remove a dependency the workflow fails since the linux images aren't updated accordingly. It's quite bothersome to have to make 2 PR's to get 1 functionality working.

With #12 we've managed to greatly reduce the amount of dockerfiles we need making it even more viable to live in the main repo.

I'd say: 

- [x] copy over the workflow
- [x] Create a directory within the main repo to hold our docker stuff
- [x] Copy over the dockerfiles + build script within that directory.
- [x] Add Docker image registry to main repository
- [x] Update build_release workflow to point to correct image repository.
- [x] Archive/remove this repository.

**Comment by Baklap4** [comment]
@ooshlablu please let me know when i can archive this project (which makes it readonly)

**Comment by ooshlablu** [comment]
@Baklap4 Go for it, everything is officially in the main repo now!
